### ISSUE TITLE
Add tool0 to URDFs

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#49] opened 2014-03-28 12:22 UTC
The `tool0` frame should be added to the UR10 & 5 URDFs.  See ros-industrial/ros_industrial_issues#24.

**Comment by gavanderhoorn** [comment] 2014-03-28 12:56
Duplicate of #34.

**Comment by fmessmer** [comment] 2015-04-21 19:46
The according discussion now takes place in #95

**Closed as completed** 2015-05-18 16:51 UTC
