### ISSUE TITLE
c++0x for fresh install

### ISSUE THREAD

**Issue by oroulet** [ros-industrial/universal_robot#273] opened 2016-12-15 14:12 UTC
just installed this driver on a new ubuntu 16.04 install with kinetic, all from deb and I had to add 
set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS}")
to ur_kinematic to make it compile.
just wanted to report

**Comment by gavanderhoorn** [comment] 2016-12-15 14:31
Thanks for reporting.

Looks like a duplicate of #254 (and then #269). Would you agree?

**Comment by gavanderhoorn** [comment] 2017-03-19 12:27
Closing due to inactivity and because `kinetic-devel` is known to build on Kinetic now.

**Closed as completed by gavanderhoorn** 2017-03-19 12:27 UTC
