### ISSUE TITLE
Revision of IO-Interface

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#118] opened 2014-09-30 12:59 UTC
The current IO-interface has been discussed in #79 and is available since #92 
However, there are some shortcomings. A revision is suggested!

As already mentioned in #106, the IO-Support needs a significant revision in order to reflect e.g. analog_input/output_range/domain as can be seen in the MasterboardData structure of deserialize.py

**Comment by gavanderhoorn** [comment] 2014-10-09 11:33
To do this properly we need to implement setters for the ranges (extension of `prog`), and take the currently configured ranges into account when converting reported analogue in / out values.

@ipa-fxm: is that a 'significant revision'? :)

**Comment by fmessmer** [comment] 2014-10-10 06:42
Yes, that's what I mean by "significant revision".
The current "IO-Interface" simply does not provide a generic IO-Interface. There is a lack of information in the current `/io-states` message (e.g. range). As well as it makes assumptions, e.g. only allows to set Voltage for analog_in/out.

Also error handling might have a potential for improvement...(see this [comment](https://github.com/ros-industrial/universal_robot/pull/117#discussion_r18220875))

**Comment by fmessmer** [comment] 2014-10-10 06:49
We should also investigate @shaun-edwards 's [comment](https://github.com/ros-industrial/universal_robot/pull/117#discussion_r18220636)

**Comment by gavanderhoorn** [comment] 2014-10-10 06:51
I don't think range should be included in the io state topic. It is only needed in the conversion to the actual value sensed by the adc, so the driver should have access to it. I'd provide getters as services to interested users, but it does not need to be included in the topic itself (as it is more of a configuration item).

**Comment by fmessmer** [comment] 2014-10-31 09:24
On more comment form @tnl-woi about IO-Interface with v3.0 that needs to be investigated:

> I checked the /io_states topic. It is published at (almost) 20 Hz.
> 
> I'm pretty sure the digital inputs and outputs are swapped: the digital_in_states properly reflect what I enter on the teach pendant, while the digital_out_states are quite noisy (i.e. toggling).
> Pins 8 and 9 are never updated. According to the documentation get_digital_in and get_digital_out are depecrated. There are now separate functions for pins 0-7 and for pins 8-9. The old function is still supported for backwards compatibility. But seeing this behavior I doubt this is the case.
> 
> The analog input and output values are always 0.0, even if I change the output using the TP. But I don't have something connected to the outputs, so I'm not sure what to expect here...

**Comment by tnl-woi** [comment] 2014-11-04 17:07
Oops! My "fix" for the v3.0 interface (in #135) was not correct. Apparently the 4 additional (undocumented) bytes are at the end, not at the beginning. The digital input fields were also increased from short to int, that's where I probably got confused...
This explains why the analog input values were not read correctly (and all other fields too, of course).

I'll try to make a new fix tomorrow.
I'm not sure how to test this properly though, since I'm not that familiar with the I/O interface yet.

**Comment by gavanderhoorn** [comment] 2014-11-05 14:00
~~@tnl-woi: I think the issue you are seeing is caused by the first few lines of 
`RobotStateRT.unpack(..)`:~~
[..]

Nope, the buffer offset is never updated in `RobotStateRT.unpack(..)`, so this is not the issue. There is still no `ptype` field in rt pkts though.

**Comment by tnl-woi** [comment] 2014-11-05 15:49
I've made a fix (#141 for Indigo, #142 for Hydro) and did some more testing:

The /io_states topic is now published at (almost) 10 Hz, as reported by rqt_topic.

Analog input/output voltage correspond to the actual measured values, but the float values reported in ROS are 10x higher than what is shown on the Teach Pendant, so I guess the division by MULT_analog_robotstate is not necessary. Was this necessary for older firmware versions?

Digital input/output bits are OK, so NOT swapped. Pins 8 and 9 are still not updated, but apparently in v3.0 firmware they are stored in the high 16-bit of the fields. This should be updated in the Python code.

So the io_states seem to be published fine now, except for the digital tool I/O pins, and the scaling of the analog values.

I also dumped the full masterboard_data object from the Python code and checked the values, which seemed alright (e.g. "48.01" for the robot_voltage_48V, etc.).

NB: I'm not sure how to continue with the above-mentioned (new) issues. Should I create separate (new) issues on GitHub to allow discussion on the solutions separately, or should we continue to post here?

**Comment by fmessmer** [comment] 2014-11-06 20:13
> The /io_states topic is now published at (almost) 10 Hz, as reported by rqt_topic.

10 Hz is the rate of the secondary communication interface...so that's fine!

> Analog input/output voltage correspond to the actual measured values, but the float values reported in ROS are 10x higher than what is shown on the Teach Pendant, so I guess the division by MULT_analog_robotstate is not necessary. Was this necessary for older firmware versions?

This particular issue is one of the reasons for IO-Interface revision!
On the pendant, a range can be selected via the drop-down menues....it's not yet fully clear to me yet...but somehow this range needs to be considered on the ROS side as well....
If I recall it correctly, the current analog values are with respect to Voltage and not Current...(or something alike...)

Also, I haven't tested the [io-interface](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/src/ur_driver/io_interface.py) since the protocol change...that should is due for revision as well.... So far, it covered some preliminary interface (which has not been there before at all)...but it turned out to not refelet the full scope of the UR IOs...

**Comment by tnl-woi** [comment] 2014-11-07 09:46
> On the pendant, a range can be selected via the drop-down menues....it's not yet fully clear to me yet...but somehow this range needs to be considered on the ROS side as well....
> If I recall it correctly, the current analog values are with respect to Voltage and not Current...(or something alike...)

I think the analog input is always a voltage indeed. The range is described in `analog_input_range{0|1}`. The analog ouput can be current or voltage (both with a fixed range), which is described in `analog_output_domain{0|1}`.

IMHO, the deserializer should not do any translation, but just pass the raw values. The user application can do the required translations. Or we should add API-functions like `get_analog_input_voltage`, which translate to proper SI units. That translation may or may not differ between firmware versions, but that should not be visible at the API boundary.

**Comment by gavanderhoorn** [comment] 2014-11-07 09:58
On 7-11-2014 10:46, Wouter van Oijen wrote:

> > On the pendant, a range can be selected via the drop-down menues....it's not yet fully clear to me yet...but somehow this range needs to be considered on the ROS side as well....
> > If I recall it correctly, the current analog values are with respect to Voltage and not Current...(or something alike...)
> 
> I think the analog input is always a voltage indeed. The range is described in `analog_input_range{0|1}`. The analog ouput can be current or voltage (both with a fixed range), which is described in `analog_output_domain{0|1}`.
> 
> IMHO, the deserializer should not do any translation, but just pass the raw values. The user application can do the required translations. Or we should add API-functions like `get_analog_input_voltage`, which translate to proper SI units. That translation may or may not differ between firmware versions, but that should not be visible at the API boundary.

I agree that the deserialiser should just deserialise. The driver should
use the information in the appropriate fields to publish the actual
values (so: properly scaled).

The driver is nothing more than a bridge, needed only because we cannot
run ROS directly on the controller (well, we can, but ignore that), and
should be as transparent as possible. We can add services to the API
that allow for retrieving the scaling parameter for ADC/DACs though.
iirc these can also be set using URScript, so that would make them
configurable from the ROS side.

Afaik btw everything is always in SI units, just scaled.

**Comment by tnl-woi** [comment] 2014-11-07 10:41
> Afaik btw everything is always in SI units, just scaled.

To clarify: I meant (and I think the term SI unit implies this, but I may be wrong about that) without scaling, so all voltages in V, currents in A, masses in kg, times in s. (Of course, ounces are also kilograms, but just scaled ;-p)

**Comment by fmessmer** [comment] 2014-11-07 16:06
That's what I meant:
Let the driver to the parsing and do all the rest in the [io-interface](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/src/ur_driver/io_interface.py)...but at the moment that interface has no means to handle the range/domain and stuff like that...that's what we need to work on...

**Comment by gavanderhoorn** [comment] 2015-02-27 10:42
As suggested in #176, I think we can get a long way by exposing / wrapping some of the URScript statements in services (for the setters). For state reporting, the current `io_states` topic is imo OK, we just need to take a look at the granularity and extend the info with how the ADCs/DACs are configured.

**Comment by gavanderhoorn** [comment] 2018-06-25 16:25
`ur_driver` is deprecated and will not see any further development.

Conceptually there are things to be reused, so this issue still contains important information, but that is not a reason to keep this issue open.

Closing this.

**Closed as completed by gavanderhoorn** 2018-06-25 16:25 UTC
Labels: enhancement
