### ISSUE TITLE
Multi-arm support

### ISSUE THREAD

**Issue by jeff-o** [ros-industrial/universal_robot#39] opened 2014-02-10 13:51 UTC
Just a quick question.  I'm not able to easily test it out myself, but does the package support multiple arms?  Naturally I'd create a custom launcher that separately names the topics published by the two arms.

**Comment by shaun-edwards** [comment] 2014-02-11 02:59
@jeff-o, launching the nodes in different namespaces would only work(simply) if the two arms had separate controllers.  I'm not sure what the dual arm setup looks like.  I would recommend sending an email to the dev list (more people watch that): swri-ros-pkg-dev@googlegroups.com

**Comment by jeff-o** [comment] 2014-02-11 03:49
Ah, there's me not being specific enough.  Yes, of course there is one arm per controller in my planned configuration.  I couldn't think of any reason why it shouldn't work, but thought I'd ask anyway.

**Comment by gavanderhoorn** [comment] 2014-02-18 11:35
Is the `ur_driver` node capable of dealing with multiple connections to the same serversocket? Or should multiple instances of that node be started? In the latter case, I think the port  `ur_driver` opens should be configurable via a launch file parameter (hard coded to be `50001` now)?

I've seen at least one [ros answers](http://answers.ros.org/question/129911/dual-arm-ur10-connection-with-universal-robot-stack/) question about this, and that person started hardcoding a different `REVERSE_PORT`.

**Comment by mikepurvis** [comment] 2014-04-16 00:29
(I'm a colleague of @jeff-o's at Clearpath)

Yes, we ran into the REVERSE_PORT issue as well. Our PC had two NICs, so our solution was simply to move one arm to a different subnet on the other NIC and then change the TCPServer code to only bind to the one interface rather than all interfaces. An obvious way to avoid the hack would be to bind TCPServer to port 0, then read out the assigned port and inject it into the prog script, ~~which could perhaps be templated using empy.~~ **I now see that prog is already being templated for the host/ip of the PC running the driver, so additionally passing in the port should be very simple.**

Thanks for the awesome job done on ur_description, by the way. Our robot description turned out to be really simple, this was basically it:

```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="husky">
  <xacro:include filename="$(find husky_description)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <ur5_robot prefix="left_arm_" />
  <ur5_robot prefix="right_arm_" />

  <joint name="base_to_left_arm" type="fixed">
    ...
  </joint>
  <joint name="base_to_right_arm" type="fixed">
    ...
  </joint>
</robot>
```

The launch setup was similarly straight-forward. Thanks again for the great work.

**Comment by Equanox** [comment] 2014-04-16 07:57
I'm with mikepurvis.

I was hardcoding the ports to launch a ur_driver node for each arm.

```
<node ns="right_arm_controller" name="ur_driver" pkg="ur_driver" type="driver_r.py" args="$(arg robot_ip_r)" output="screen" />
<node ns="left_arm_controller" name="ur_driver" pkg="ur_driver" type="driver_l.py" args="$(arg robot_ip_l)" output="screen" />
```

But obviously it would be nice to pass the port as an additional argument.

**Comment by gavanderhoorn** [comment] 2014-04-16 09:53
@mikepurvis wrote:

> [..] I now see that prog is already being templated for the host/ip of the PC running the driver, so additionally passing in the port should be very simple.

Indeed, I was going to suggest the same thing. This should not be too hard to implement.

I suggest just adding an additional launch file argument, with a default value being the currently used port. This would keep things backwards compatible, while also addressing the issues raised here.

**Comment by mikepurvis** [comment] 2014-04-16 10:58
What would be broken by having the OS simply select the port at runtime? Seems an unnecessary parameterization when it could just do the right thing in the background without bothering the user.

**Comment by gavanderhoorn** [comment] 2014-04-16 11:04
@mikepurvis wrote:

> What would be broken by having the OS simply select the port at runtime? Seems an unnecessary parameterization when it could just do the right thing in the background without bothering the user.

I don't know, but I think it would be a good idea to still have the option of configuring the driver to use a specific port. The reason I suggested the default to be the port that is currently in use (50001) is to keep things 'as they are/were'. We can't know all current uses of the driver, so we can't predict in what way the assumption of that port being used influences other peoples' software.

**Comment by fmessmer** [comment] 2014-04-17 09:45
I don't want to make a big deal out of this - not bigger than necessary...
But, isn't this issue a direct consequence from not being able to properly configure/parametrize the ur_driver? I mean, there is not only the PORT hard-coded in driver.py and using arguments, when there are yaml's and the parameter server...? Also, the classes are still called UR5\* when they are also used on the UR10 (see #2)....
Should the solution for this issue be another hack or is there a need for re-writing the driver (maybe for Indigo)?

**Comment by gavanderhoorn** [comment] 2014-04-17 10:16
@ipa-fxm wrote:

> But, isn't this issue a direct consequence from not being able to properly configure/parametrize the ur_driver? I mean, there is not only the PORT hard-coded in driver.py and using arguments, when there are yaml's and the parameter server...?

using parameters in launchfiles uses the parameter server, yaml files could also be loaded, but wouldn't that use the same infrastructure?

> Also, the classes are still called UR5\* when they are also used on the UR10 (see #2)....
> Should the solution for this issue be another hack or is there a need for re-writing the driver (maybe for Indigo)?

The current implementation could use some TLC, I guess we all agree on that. A rewrite seems a bit involved, I would think just addressing the issues you describe one at a time properly would not result in additional _hacks_.

**Comment by shaun-edwards** [comment] 2014-04-17 22:01
@mikepurvis wrote:

> What would be broken by having the OS simply select the port at runtime? Seems an unnecessary parameterization when it could just do the right thing in the background without bothering the user.

Can this work?  Doesn't the ROS PC(client) and the controller(server) have to connect on the same port in order to talk.  If each respective OS chose an arbitrary port, how would the connect?  On other robots, the ports are typically _hard-coded_ due to limited capabilities.

@ipa-fxm  wrote:

> Should the solution for this issue be another hack or is there a need for re-writing the driver (maybe for Indigo)?

I think we can address these smaller issues as @gavanderhoorn has said without too much issue.  I would like to see the driver written to utilize the standard ROS-Industrial client, which I believe is more deterministic.  However, this isn't really practical given this driver works well for a number of people.

**Comment by mikepurvis** [comment] 2014-04-17 22:59
> Doesn't the ROS PC(client) and the controller(server) have to connect on the same port in order to talk.

Not at all. All the outgoing connections from your browser to webservers leave on randomly-assigned ports, but are connecting to port 80 on the servers.

This is complicated by the fact that there are actually two connections happening. The driver initially connects to the UR controller at controller_ip:30002, and downloads a script. This is a very ordinary thing, and this could happen many times in parallel with no problem.

The issue is that the script prompts the driver to then attempt to connect _back_ to a TCP server on the robot PC. It's the creation of that server which is the problem, because multiple instances of the driver can't each have a server on port 50001. However, since the specification of the port to connect back to is included in the downloaded script, it's trivial to just set it to whatever port happened to be available for the server to start on.

**Comment by fmessmer** [comment] 2014-04-23 12:46
In PR #66 the reverse_port is now configurable as well using an additional second [optional] launch file argument (similar to hostname for setting the IP).
If no additional argument for the reverse_port is given, the default port 50001 is used.

**Comment by abubeck** [comment] 2014-08-06 11:33
This was merged. I will close this issue.

**Closed as completed by abubeck** 2014-08-06 11:33 UTC

**Comment by houlei516** [comment] 2018-09-09 08:40
Could you please update the above support to ur_modern_driver. Expect a generic solution. Hope to coordinate two UR10 for different tasks, other than master-slave. 

Tried out this solution. https://answers.ros.org/question/269074/dual-arm-ur5-connection-with-universal-robot-stack/

**Comment by gavanderhoorn** [comment] 2018-09-09 08:43
@houlei516: if you are having specific issues with `ur_modern_driver`, then please post an issue over at [ur_modern_driver/issues](https://github.com/ThomasTimm/ur_modern_driver/issues).

The issue you commented on in this repository is 4 years old, closed and is not about `ur_modern_driver`.
