### ISSUE TITLE
Semantic description is not specified for the same robot as the URDF

### ISSUE THREAD

**Issue by keke-220** [ros-industrial/universal_robot#563] opened 2021-01-29 01:19 UTC
I am trying to run ur5e on gazebo. When I run "roslaunch ur5_e_moveit_config ur5_e_moveit_planning_execution.launch limited:=true", it shows some errors:

```
[ERROR] [1611882469.871418732]: Semantic description is not specified for the same robot as the URDF
[ERROR] [1611882469.872031288]: Link 'ee_link' declared as part of a chain in group 'manipulator' is not known to the URDF
[ERROR] [1611882469.872057281]: Link 'ee_link' declared as part of group 'endeffector' is not known to the URDF
[ERROR] [1611882469.872129461]: Link 'ee_link' specified as parent for end effector 'moveit_ee' is not known to the URDF
[ERROR] [1611882469.898956814]: Group state 'home' specified for group 'manipulator', but that group does not exist
[ERROR] [1611882469.898964819]: Group state 'up' specified for group 'manipulator', but that group does not exist
[ERROR] [1611882469.946106525]: Failed to find 3D sensor plugin parameters for octomap generation
```

Does anyone know how it deal with it? Thanks!

<details>
<summary>full `roslaunch` output</summary>

```
SUMMARY
========

PARAMETERS
 * /move_group/allow_trajectory_execution: True
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'action_ns': 'f...
 * /move_group/endeffector/planner_configs: ['SBLkConfigDefau...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/manipulator/default_planner_config: RRTConnectkConfig...
 * /move_group/manipulator/longest_valid_segment_fraction: 0.01
 * /move_group/manipulator/planner_configs: ['SBLkConfigDefau...
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/execution_duration_monitoring: False
 * /move_group/use_controller_manager: False
 * /robot_description_kinematics/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/elbow_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/elbow_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/elbow_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/elbow_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/shoulder_lift_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/shoulder_lift_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_lift_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/shoulder_lift_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_velocity: 3.14
 * /robot_description_planning/joint_limits/wrist_1_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_1_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_1_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_1_joint/max_velocity: 6.28
 * /robot_description_planning/joint_limits/wrist_2_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_2_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_2_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_2_joint/max_velocity: 6.28
 * /robot_description_planning/joint_limits/wrist_3_joint/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/wrist_3_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_3_joint/max_acceleration: 3.14
 * /robot_description_planning/joint_limits/wrist_3_joint/max_velocity: 6.28
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    move_group (moveit_ros_move_group/move_group)

ROS_MASTER_URI=http://localhost:11311

process[move_group-1]: started with pid [21746]
[ERROR] [1611882469.871418732]: Semantic description is not specified for the same robot as the URDF
[ERROR] [1611882469.872031288]: Link 'ee_link' declared as part of a chain in group 'manipulator' is not known to the URDF
[ WARN] [1611882469.872044995]: Group 'manipulator' is empty.
[ERROR] [1611882469.872057281]: Link 'ee_link' declared as part of group 'endeffector' is not known to the URDF
[ WARN] [1611882469.872064612]: Group 'endeffector' is empty.
[ERROR] [1611882469.872129461]: Link 'ee_link' specified as parent for end effector 'moveit_ee' is not known to the URDF
[ WARN] [1611882469.872149077]: Link 'ee_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1611882469.872158185]: Link 'ee_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1611882469.872166118]: Link 'ee_link' is not known to URDF. Cannot disable collisons.
[ INFO] [1611882469.872217846]: Loading robot model 'ur_robot_gazebo'...
[ WARN] [1611882469.872239870]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1611882469.872254957]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1611882469.898907322]: Group 'manipulator' must have at least one valid joint
[ WARN] [1611882469.898931824]: Failed to add group 'manipulator'
[ WARN] [1611882469.898938795]: Group 'endeffector' must have at least one valid joint
[ WARN] [1611882469.898944166]: Failed to add group 'endeffector'
[ERROR] [1611882469.898956814]: Group state 'home' specified for group 'manipulator', but that group does not exist
[ERROR] [1611882469.898964819]: Group state 'up' specified for group 'manipulator', but that group does not exist
[ WARN] [1611882469.907868868]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/manipulator/kinematics_solver_attempts' from your configuration.
[ INFO] [1611882469.940500411]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1611882469.942018602]: MoveGroup debug mode is OFF
Starting planning scene monitors...
[ INFO] [1611882469.942038204]: Starting planning scene monitor
[ INFO] [1611882469.943326055]: Listening to '/planning_scene'
[ INFO] [1611882469.943341489]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1611882469.944664262]: Listening to '/collision_object'
[ INFO] [1611882469.945720626]: Listening to '/planning_scene_world' for planning scene world geometry
[ERROR] [1611882469.946106525]: Failed to find 3D sensor plugin parameters for octomap generation
[ INFO] [1611882469.951843723]: Listening to '/attached_collision_object' for attached collision objects
Planning scene monitors started.
[ INFO] [1611882469.969214557]: Initializing OMPL interface using ROS parameters
[ INFO] [1611882469.974896162]: Using planning interface 'OMPL'
[ INFO] [1611882469.977057666]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1611882469.977299649]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1611882469.977530762]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1611882469.977792460]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1611882469.978038576]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1611882469.978269045]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1611882469.978300275]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1611882469.978311842]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1611882469.978319530]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1611882469.978329701]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1611882469.978339690]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1611882470.419841330, 719.629000000]: Added FollowJointTrajectory controller for pos_joint_traj_controller
[ INFO] [1611882470.420030636, 719.630000000]: Returned 1 controllers in list
[ INFO] [1611882470.440903532, 719.651000000]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1611882470.541863898, 719.752000000]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1611882470.541962713, 719.752000000]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1611882470.542005274, 719.752000000]: MoveGroup context initialization complete

You can start planning now!
```

</details>

**Comment by keke-220** [comment] 2021-01-29 01:29
I was running the melodic-devel-staging branch on Melodic.
And I was planning to run:
 roslaunch ur_gazebo ur5e_bringup.launch limited:=true
roslaunch ur5_e_moveit_config ur5_e_moveit_planning_execution.launch
roslaunch ur5_e_moveit_config moveit_rviz.launch config:=true
Did I miss anything?

**Comment by gavanderhoorn** [comment] 2021-01-29 09:39
There is no MoveIt support in `melodic-devel-staging`.

See #538.

**Comment by gavanderhoorn** [comment] 2021-01-29 09:40
As I believe we've identified the cause of the problem you report, I'm going to close this issue.

If it turns out that was not the cause, we can re-open.

In the meantime, feel free to keep commenting on it.

**Comment by gavanderhoorn** [comment] 2021-01-29 09:40
Finally: please note that `melodic-devel-staging` is just that, a *staging ground*. It's not a released branch at the moment, so things may -- and likely will -- break at any time.

**Closed as completed by gavanderhoorn** 2021-01-29 09:40 UTC
