### ISSUE TITLE
Gazebo robot moving dashed

### ISSUE THREAD

**Issue by omeranar1** [ros-industrial/universal_robot#569] opened 2021-04-22 13:26 UTC
i run ur robot in "gazebo+rviz+ur5_moveit_planning_execution".
I am sending waypoints with using cpp code.
i am doing "computeCartesianPath" for drawing a single line,
i create two point x0=-500 and x1=+500,
But when the robot in the gazebo moves on the line, it sometimes slows down then returns to its normal speed. 

![2021-04-22-165252_3840x1080_scrot](https://user-images.githubusercontent.com/19305324/115726751-ae995c80-a38b-11eb-92b3-70d61df309b9.png)

**Comment by gavanderhoorn** [comment] 2021-04-22 14:36
This reads like a duplicate of [gazebo robot slows down then returns normal speed](https://answers.ros.org/question/376730) on ROS Answers.

Please don't cross-post.

I'll close your post here.

**Closed as completed by gavanderhoorn** 2021-04-22 14:36 UTC
