### ISSUE TITLE
UR urdf

### ISSUE THREAD

**Issue by ghx-0228** [ros-industrial/universal_robot#447] opened 2019-07-12 06:27 UTC
Hey, I am just curious about a problem with the UR simulation in Gazebo.

I find all links connected to "wrist_3_link" can not display in the structure tree at left panel, like "ee_link" or "tool0".  But  they indeed are in the model, after adding visual property for them in urdf, we can see them emerge in Scene zone. I infer and find they all become the nested model of "wrist_3_link".   However, I check the urdf file and did not find what makes these model become nested model. So could you help me or tell me how to implement this in urdf.
![image](https://user-images.githubusercontent.com/47413096/61106477-e2094080-a4af-11e9-8063-f9adf4e833fa.png)

**Comment by gavanderhoorn** [comment] 2019-07-12 07:40
<del>Does your model look like the one shown in #400?</del>

<del>If so: check whether #374 describes your situation and the solution.</del>

hm, wait, your description sounds different.

> I find all links connected to "wrist_3_link" can not display in the structure tree at left panel, like "ee_link" or "tool0".

`ee_link` and `tool0` don't have any `visual` or `collision` geometry, so they cannot be "seen" in the simulation, as they are merely coordinate frames. Not actual physical links of the robot.

**Comment by gavanderhoorn** [comment] 2019-07-12 07:42
I'm going to close this for now as I believe this is a user-side configuration issue (caused by ros/urdfdom_headers#41).

If it turns out that is not the cause, we can re-open.

**Closed as completed by gavanderhoorn** 2019-07-12 07:42 UTC
Labels: works-for-me

**Comment by ghx-0228** [comment] 2019-07-12 08:07
Thanks for your reply.
I have also tried to add visual and collision properties for ee_link. But the result is the same. We can see there is a grey box on the UR but can not see in the structure tree. 
![image](https://user-images.githubusercontent.com/47413096/61112380-46cb9780-a4be-11e9-8ec1-caa9b20f7d36.png)
Additionally, if I connect a part to "wrist_3_link", it can be one part with "wrist_3_link" instead of  a separate part.
![image](https://user-images.githubusercontent.com/47413096/61112709-0fa9b600-a4bf-11e9-97d1-e8088718904c.png)

**Comment by gavanderhoorn** [comment] 2019-07-12 08:25
Ok, I believe I know what is going on.

First a general comment:

> I have also tried to add visual and collision properties for ee_link. 

`ee_link` and `tool0` are not supposed to be edited. You should not add `visual` nor `collision` geometry to them, nor should you edit their location.

`ee_link` is deprecated and will go away. A `flange` frame will be added instead.

> But the result is the same. We can see there is a grey box on the UR but can not see in the structure tree.

This is a property of Gazebo: when loading a `.urdf`, Gazebo will merge all links that are only connected via `fixed` joints.

As both `ee_link` and `tool0` are connected via a `fixed` joint to `wrist_3_link`, you will not find `ee_link` nor `tool0` in the model tree of Gazebo, as they are pruned from the model.

This is something that Gazebo does. We can't influence that.

---

Edit: the same holds for your EEF: if you connect that to any link in the robot with a `fixed` joint, Gazebo will merge the `link` that is connected to that `fixed` joint with the `link` of the robot that you selected as a `parent`.

**Comment by ghx-0228** [comment] 2019-07-12 08:53
OK, get it. Thanks very much!
