### ISSUE TITLE
moveit_cfgs: traj exec mon params need to be pushed down into ns

### ISSUE THREAD

**Issue by scottpaulin** [ros-industrial/universal_robot#263] opened 2016-09-21 12:10 UTC
Not sure if anyone else has noticed these warnings or how long they have been around for. I am using ros kinetic binaries with a source install of Moveit on Ubuntu 16.04.

> roslaunch ur_gazebo ur5.launch

Gives these warnings: 

> xacro: Traditional processing is deprecated. Switch to --inorder processing!
> To check for compatibility of your document, use option --check-order.
> For more infos, see http://wiki.ros.org/xacro#Processing_Order
> deprecated: xacro tags should be prepended with 'xacro' xml namespace.
> Use the following script to fix incorrect usage:
>         find . -iname "*.xacro" | xargs sed -i 's#<([/]\?)(if|unless|include|arg|property|macro|insert_block)#<\1xacro:\2#g'
> when processing file: /home/scott/test_ur_workspace/src/universal_robot/ur_description/urdf/ur5_joint_limited_robot.urdf.xacro
> 
> redefining global property: pi
> when processing file: /home/scott/test_ur_workspace/src/universal_robot/ur_description/urdf/ur5_joint_limited_robot.urdf.xacro
> xacro.py is deprecated; please use xacro instead

And this:

> roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true 

Gives these warnings:

> [ WARN] [1474452011.197816005, 88.442000000]: 
> Deprecation warning: parameter 'allowed_execution_duration_scaling' moved into namespace 'trajectory_execution'.
> Please, adjust file trajectory_execution.launch.xml!
> [ WARN] [1474452011.198551320, 88.443000000]: 
> Deprecation warning: parameter 'allowed_goal_duration_margin' moved into namespace 'trajectory_execution'.
> Please, adjust file trajectory_execution.launch.xml!

**Comment by scottpaulin** [comment] 2016-09-21 12:12
It looks like  open PR #251 fixes the xacro warnings

**Comment by gavanderhoorn** [comment] 2016-09-21 19:00
This is a known issue, and #251 does indeed fix it.

**Comment by gavanderhoorn** [comment] 2016-09-21 19:01
I'm going to close this as a _duplicate_, although technically it's only a duplicate of a non-existent issue (the one that made @davetcoleman submit that PR).

**Comment by gavanderhoorn** [comment] 2016-09-21 19:01
But thanks for reporting @scottpaulin.

**Comment by gavanderhoorn** [comment] 2016-09-22 06:53
Re-opening as the second warning is actually not related to the xacros, but to the recent changes to the trajectory execution monitor parameters in MoveIt.

**Comment by gavanderhoorn** [comment] 2017-09-13 00:09
Namespace issue was fixed with the merge of #285.

**Closed as completed by gavanderhoorn** 2017-09-13 00:09 UTC
Labels: enhancement
